### ISSUE TITLE
Fatal Python error: Py_Initialize: unable to load the file system codec

### ISSUE THREAD

**Issue by ConductedForce** [jonburesh/sintelgame#2]
I get this error when running sintel_the_game.blend or sintel_the_game.exe files. Running in blender also produces result. Happens in 32/64 bit versions.

Debugging in Visual Studio 2015 gives me this warning. Otherwise I get "Runtime Error!" and the game crashes. 

Also occurs even if an external version of python is installed (not the included version from blender). 

Blender ver 2.78c
Python ver 3.5.2 (both from blender and external installation) (64bit)
Running Windows 7 64bit

**Comment by ConductedForce** [comment]
It may also be important to note that I am using the Blender version from Steam.

**Comment by ConductedForce** [comment]
Have output from Blender console upon Runtime Error:

Blender Game Engine Started
AL lib: <EE> alc_cleanup: 1 device not closed
Color management: using fallback mode for management
BLF_lang_init: 'locale' data path for translations not found, continuing
**(This showed up before runtime error^)**
Detected GL_ARB_texture_env_combine
Detected GL_ARB_texture_cube_map
Detected GL_ARB_multitexture
Detected GL_ARB_shader_objects
Detected GL_ARB_vertex_shader
Detected GL_ARB_fragment_shader
Detected GL_ARB_vertex_program
Detected GL_ARB_depth_texture
Detected GL_EXT_separate_specular_color
Warning! bundled python not found and is expected on this platform. (if you built with CMake: 'install' target may not have been built)
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module name 'encodings'

**Comment by ConductedForce** [comment]
Blender Python Console seems to import encodings just fine. Still researching "codec" error.

**Comment by ConductedForce** [comment]
created PYTHONHOME temporarily and it still crashed but didn't produce a Runtime Error.

**Comment by ConductedForce** [comment]
Tried installing blender from installer, failed with that setup as well. I'm certain it has something to do with the python setup from Blender.

**Comment by ConductedForce** [comment]
Got Blender to alternate between bundled and non-bundled versions of python. Still failed.

**Comment by ConductedForce** [comment]
DEVELOPMENT! Maybe... tried the "run_exe.py" and it failed, stating that No module named 'bge' exists.

**Comment by ConductedForce** [comment]
Stuck a print statement in run_exe.py, apparently it keeps failing in the try loop. Realized try block doesn't have to succeed..

**Comment by ConductedForce** [comment]
Run_exe.py is not the problem.

**Comment by ConductedForce** [comment]
You may not believe this, but running sintel_win.blend works by itself.

**Comment by ConductedForce** [comment]
Game works with following command line syntax (cmd.exe): blenderplayer.exe -f c:\path\to\sintel_win.blend

Using same settings listed earlier
Win 7
Python 3.5.2 (64bit)
Blender 2.78c (64bit) (latest as of this issue)
Sintel codebase at the time of this issue

**Comment by jonburesh** [comment]
That's good news! Glad you were able to get it working 👍

**Comment by Fojtik** [comment]
Please do not distribute/publish executables that will crash only.

**Comment by scorninpc** [comment]
@Fojtik , you are advising about executable published 1 year ago . If I can advise you, do not try run old executables thinking it will run at the first

Try help, not revive old things

**Comment by Fojtik** [comment]
Sorry, but I have downloaded the latest executables available. I has been writing just here, because I am solving similiar problem.

This is the bleeding edge of your project,
https://github.com/jonburesh/sintelgame
or is there something else?

I have tested first .zip download, but the zip file is corrupted and cannot be unpacked
https://sintel-the-game.en.uptodown.com/windows/download
the only set of something is in the git repo.

Or where to find latest executables?

**Comment by scorninpc** [comment]
The link of ziped file are from 5 years ago. The last commit are from 2 year ago. The blender player had alot changes from the last years

Try an old blender player version, ou try debug what causing the problem to downgrade that

**Comment by jonburesh** [comment]
The target blender version is [2.68](http://download.blender.org/release/Blender2.68/). 

The uptodown.com page is **not** associated with sintel the game and I wouldn't trust that download. The latest code will always be here on github.
