### ISSUE TITLE
It is impossible to run executables. They are immediatelly crassing.

### ISSUE THREAD

**Issue by Fojtik** [jonburesh/sintelgame#3]
I has been tested Windows XP32, Windows 7 - 32, Windows 10 and the result is allways same. All executables immediately crash.
![sintelcrash](https://user-images.githubusercontent.com/2893993/45012298-c4a95180-b016-11e8-9c1c-a507be0bab25.gif)

Messages from VisualStudio debugger:
```
sintel_the_game.exe': Loaded 'C:\Windows\System32\hid.dll'
'sintel_the_game.exe': Loaded 'C:\Windows\System32\cryptsp.dll'
'sintel_the_game.exe': Loaded 'C:\Windows\System32\rsaenh.dll'
**Fatal Python error: Py_Initialize: unable to load the file system codec**
The thread 'Win32 Thread' (0xe68) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0x5dc) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0x104) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0x280) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xb58) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xc50) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xee8) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xa68) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0x12c) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xdc4) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xad0) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xc1c) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xe1c) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xe48) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xd04) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0xd78) has exited with code 3 (0x3).
The thread 'Win32 Thread' (0x1c4) has exited with code 3 (0x3).
The program '[3416] sintel_the_game.exe: Native' has exited with code 3 (0x3).

```

**Comment by Fojtik** [comment]
I have noted this, https://github.com/jonburesh/sintelgame/issues/2
there is some critical defect behind all executables. It would be best to drop some word in documentation that
**blenderplayer.exe R:\sintelgame-master\sintel_win\sintel_win.blend** is the only way, how torun at least something.

**Comment by jonburesh** [comment]
Fojtik, please see https://github.com/jonburesh/sintelgame/commit/292e28020b2a9d5cf9fed47746e8b8d4036a4a4c

**Comment by Fojtik** [comment]
Yes, some little improvement. This readme does not explicitly state that the Blender *MUST* be installed to run your game. I understand it - that you specify Blender version. For package with size 900MB I would expect that it will bundle its DLLs.

Anyway, when average user runs your executable, he/she will obtain the crash message box only. Be sure that he will not run Visual Studio to analyze problem details.
